import Head from "next/head";
import Main from "../components/Main";

// export const getStaticProps = async () => {
//   return { props: { posts: [{ title: "Hello World" }] } };
// };

export default function Home({ posts }) {
  return (
    <div className="mx-auto my-0">
      <Head>
        <title>Simple Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      {/* {posts.map((post) => (
        <div key={post.title}>{post.title}</div>
      ))} */}
    </div>
  );
}
