import Head from "next/head";
import PostCard from "../components/PostCard";
import { useQuery } from "@tanstack/react-query";

export const getStaticProps = async () => {
  const data = await getBlogposts();
  return { props: { posts: data } };
};

async function getBlogposts() {
  const data = await fetch("/api/blogposts").then((res) => res.json());
  return data;
}

export default function Home({ posts }) {
  const { data } = useQuery(["posts"], getBlogposts, {
    initialData: posts,
    refetchInterval: 5000,
  });

  return (
    <div className="mx-auto my-0">
      <Head>
        <title>Simple Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="container mx-auto flex flex-col gap-5 py-8">
        <div className="text-2xl">Posts</div>
        {data?.map((post) => (
          <PostCard key={post.id} post={post} />
        ))}
      </section>
    </div>
  );
}
